configs:
  newrelic_config:
    file: ./newrelic.ini
services:
  local:  # for local development
    build: .
    ports:
      - "8000:8000"
    command: newrelic-admin run-program uvicorn --reload --lifespan off --host 0.0.0.0 orthocal.asgi:application
    volumes:
      - .:/orthocal:consistent
    environment:
      - PORT=8000
      - ALLOWED_HOSTS=localhost
  web:  # Use to test as it will be deployed in production
    build: .
    ports:
      - "8000:8000"
    cpu_count: 4
    environment:
      - PORT=8000
      - ALLOWED_HOSTS=localhost
      - NEW_RELIC_CONFIG_FILE=/orthocal-secrets/newrelic.ini
      - NEW_RELIC_ENVIRONMENT=development
      - WEB_CONCURRENCY=4
    configs:
      - source: newrelic_config
        target: /orthocal-secrets/newrelic.ini
  tests:
    build: .
    command: ./manage.py test --keepdb
