# Generated by Django 4.1.4 on 2023-01-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composite',
            old_name='reading',
            new_name='content',
        ),
    ]
