# Generated by Django 4.1.4 on 2023-01-23 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0002_rename_reading_composite_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='pericope_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendarium.pericope'),
        ),
    ]
