# Generated by Django 5.1 on 2026-07-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0001_squashed_0003_rename_day_month_day_calendarium_month_f3d07a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='tradition',
            field=models.CharField(choices=[('common', 'Common'), ('slavic', 'Slavic-specific'), ('greek', 'Greek-specific')], default='common', max_length=16),
        ),
    ]
