# Generated by Django 6.0.6 on 2026-07-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0004_reading_tradition'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='tradition',
            field=models.CharField(choices=[('common', 'Common'), ('slavic', 'Slavic-specific'), ('greek', 'Greek-specific')], default='common', max_length=16),
        ),
    ]
