# Generated by Django 4.1.4 on 2023-01-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0004_remove_reading_pericope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='pericope_link',
            new_name='pericope',
        ),
    ]
