# Generated by Django 6.0.6 on 2026-07-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0005_day_tradition'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='saints',
            field=models.JSONField(default=list),
        ),
    ]
