# Generated by Django 4.1.4 on 2023-01-23 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0005_rename_pericope_link_reading_pericope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='pericope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.pericope'),
        ),
    ]
