# Generated by Django 6.0.6 on 2026-07-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0006_day_saints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='saint',
        ),
    ]
