# Generated by Django 6.0.6 on 2026-07-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0007_remove_day_saint'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
