# Generated by Django 4.1.4 on 2023-01-24 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0007_remove_reading_book'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='pericope',
            index_together=set(),
        ),
    ]
