# Generated by Django 6.0.7 on 2026-08-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0008_day_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='saints',
        ),
    ]
