# Generated by Django 6.1 on 2026-08-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0009_remove_day_saints'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdoReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(choices=[('greek', 'Greek (GOA)'), ('antiochian', 'Antiochian')], max_length=16)),
                ('year', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('day', models.SmallIntegerField()),
                ('source', models.CharField(max_length=64)),
                ('pdist', models.SmallIntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['jurisdiction', 'year', 'month', 'day'], name='calendarium_jurisdi_dd1cfe_idx')],
                'constraints': [models.UniqueConstraint(fields=('jurisdiction', 'year', 'month', 'day', 'source'), name='unique_ordo_reading')],
            },
        ),
    ]
