# Generated by Django 6.1 on 2026-08-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0010_ordoreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='tradition',
            field=models.CharField(choices=[('common', 'Common'), ('slavic', 'Slavic-specific'), ('greek', 'Greek-specific'), ('antiochian', 'Antiochian-specific')], default='common', max_length=16),
        ),
        migrations.AlterField(
            model_name='reading',
            name='tradition',
            field=models.CharField(choices=[('common', 'Common'), ('slavic', 'Slavic-specific'), ('greek', 'Greek-specific'), ('antiochian', 'Antiochian-specific')], default='common', max_length=16),
        ),
    ]
