# Generated by Django 6.1 on 2026-09-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0010_ordoreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='fast',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='fast_exception',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='feast_level',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
