# Generated by Django 6.1 on 2026-09-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0011_alter_day_fast_alter_day_fast_exception_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='fast_cap_exempt',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
