# Generated by Django 4.1.4 on 2022-12-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=3)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('content', models.TextField()),
                ('language', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('book', 'chapter', 'verse', 'language')},
                'index_together': {('book', 'chapter', 'verse', 'language')},
            },
        ),
    ]
