# Generated by Django 4.1.7 on 2023-03-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(db_index=True, max_length=3)),
                ('chapter', models.IntegerField(db_index=True)),
                ('verse', models.IntegerField(db_index=True)),
                ('content', models.TextField()),
                ('paragraph_start', models.BooleanField(default=False)),
                ('language', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('book', 'chapter', 'verse', 'language')},
            },
        ),
    ]
