# Generated by Django 4.1.4 on 2022-12-13 19:16

from django.db import migrations

from bible.parse import parse_usfx

def load_default_scriptures(apps, schema_editor):
    Verse = apps.get_model('bible', 'Verse')
    for verse in parse_usfx('data/eng-kjv_usfx.xml'):
        Verse.objects.create(**verse)

def unload_default_scriptures(apps, schema_editor):
    Verse = apps.get_model('bible', 'Verse')
    Verse.objects.filter(language='eng').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_default_scriptures, unload_default_scriptures),
    ]
