# Generated by Django 6.0.7 on 2026-07-30 20:26

from django.db import migrations, models


def backfill_translations(apps, schema_editor):
    # AddField's default only gives every existing row 'kjv' -- correct for
    # the English rows, wrong for Romanian/Serbian, which were never KJV.
    Verse = apps.get_model('bible', 'Verse')
    Verse.objects.filter(language='ro').update(translation='rccv')
    Verse.objects.filter(language='sr').update(translation='srp1865')


def unbackfill_translations(apps, schema_editor):
    Verse = apps.get_model('bible', 'Verse')
    Verse.objects.filter(language__in=('ro', 'sr')).update(translation='kjv')


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_load_scriptures'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='verse',
            name='translation',
            field=models.CharField(default='kjv', max_length=20),
        ),
        migrations.RunPython(backfill_translations, unbackfill_translations),
        migrations.AlterUniqueTogether(
            name='verse',
            unique_together={('book', 'chapter', 'verse', 'language', 'translation')},
        ),
    ]
