# Generated by Django 4.1.4 on 2023-01-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commemoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('high_rank', models.BooleanField()),
                ('month', models.SmallIntegerField()),
                ('day', models.SmallIntegerField(blank=True, null=True)),
                ('story', models.TextField()),
            ],
        ),
    ]
