# Generated by Django 4.1.4 on 2023-01-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commemorations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commemoration',
            unique_together={('month', 'day', 'title')},
        ),
    ]
