# Generated by Django 4.1.4 on 2023-01-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commemorations', '0004_alter_commemoration_options_commemoration_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commemoration',
            name='day',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='commemoration',
            name='month',
            field=models.SmallIntegerField(db_index=True),
        ),
    ]
