# Generated by Django 4.1.6 on 2023-02-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commemorations', '0005_alter_commemoration_day_alter_commemoration_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='commemoration',
            name='alt_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
