# Generated by Django 6.0.6 on 2026-07-28 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarium', '0008_day_story'),
        ('commemorations', '0006_commemoration_alt_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('story', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayCommemoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.SmallIntegerField(default=0)),
                ('new_style', models.BooleanField(default=False)),
                ('ordering', models.SmallIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.day')),
                ('saint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commemorations.saint')),
            ],
            options={
                'ordering': ('ordering',),
                'unique_together': {('day', 'saint')},
            },
        ),
    ]
