# Generated by Django 6.0.6 on 2026-07-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commemorations', '0007_saint_daycommemoration'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycommemoration',
            name='day_native',
            field=models.BooleanField(default=True),
        ),
    ]
