# Generated by Django 6.0.7 on 2026-07-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commemorations', '0008_daycommemoration_day_native'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycommemoration',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daycommemoration',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='saint',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
