# Generated by Django 6.0.7 on 2026-07-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commemorations', '0009_remove_saint_story_daycommemoration_story_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saint',
            name='story',
        ),
    ]
