# Generated by Django 6.0.7 on 2026-07-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commemorations', '0010_remove_saint_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycommemoration',
            name='tradition',
            field=models.CharField(choices=[('common', 'Common'), ('slavic', 'Slavic-specific'), ('greek', 'Greek-specific')], default='common', max_length=16),
        ),
    ]
