# Generated by Django 6.0.7 on 2026-07-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commemorations', '0011_daycommemoration_tradition'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycommemoration',
            name='high_rank',
            field=models.BooleanField(default=False),
        ),
    ]
