# Generated by Django 6.0.7 on 2026-07-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commemorations', '0012_daycommemoration_high_rank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commemoration',
        ),
    ]
