# Generated by Django 6.0.7 on 2026-07-28 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commemorations', '0013_delete_commemoration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycommemoration',
            name='saint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commemorations.saint'),
        ),
    ]
