# Generated by Django 6.0.7 on 2026-08-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commemorations', '0014_alter_daycommemoration_saint'),
    ]

    operations = [
        migrations.AddField(
            model_name='saint',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
