# Generated by Django 6.0.7 on 2026-08-13 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commemorations', '0015_saint_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='daycommemoration',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='DayCommemorationSaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=1)),
                ('commemoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commemorations.daycommemoration')),
                ('saint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commemorations.saint')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('commemoration', 'saint')},
            },
        ),
        migrations.AddField(
            model_name='daycommemoration',
            name='saints',
            field=models.ManyToManyField(blank=True, through='commemorations.DayCommemorationSaint', to='commemorations.saint'),
        ),
        migrations.RemoveField(
            model_name='daycommemoration',
            name='saint',
        ),
    ]
