# Generated by Django 6.0.7 on 2026-08-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commemorations', '0016_alter_daycommemoration_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saint',
            name='normalized_name',
            field=models.CharField(blank=True, default='', max_length=410),
        ),
    ]
